/*
 * Mushotoku — a privacy-focused, offline productivity app.
 * Copyright (C) 2026 Tom Frischmuth
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.mushotoku.app.holidays

import android.content.Context
import android.content.res.Configuration
import com.mushotoku.app.R
import java.util.Locale

fun Context.localizedFor(locale: Locale): Context =
    createConfigurationContext(Configuration(resources.configuration).apply { setLocale(locale) })

object HolidayNames {

    private val byKey: Map<String, Int> = mapOf(
        "country_de" to R.string.country_de,
        "country_at" to R.string.country_at,
        "country_ch" to R.string.country_ch,
        "country_fr" to R.string.country_fr,
        "country_it" to R.string.country_it,
        "country_es" to R.string.country_es,
        "country_nl" to R.string.country_nl,
        "country_pl" to R.string.country_pl,
        "country_gb" to R.string.country_gb,
        "country_us" to R.string.country_us,
        "region_nationwide" to R.string.region_nationwide,
        "region_de_bw" to R.string.region_de_bw,
        "region_de_by" to R.string.region_de_by,
        "region_de_be" to R.string.region_de_be,
        "region_de_bb" to R.string.region_de_bb,
        "region_de_hb" to R.string.region_de_hb,
        "region_de_hh" to R.string.region_de_hh,
        "region_de_he" to R.string.region_de_he,
        "region_de_mv" to R.string.region_de_mv,
        "region_de_ni" to R.string.region_de_ni,
        "region_de_nw" to R.string.region_de_nw,
        "region_de_rp" to R.string.region_de_rp,
        "region_de_sl" to R.string.region_de_sl,
        "region_de_sn" to R.string.region_de_sn,
        "region_de_st" to R.string.region_de_st,
        "region_de_sh" to R.string.region_de_sh,
        "region_de_th" to R.string.region_de_th,
        "holiday_de_neujahr" to R.string.holiday_de_neujahr,
        "holiday_de_karfreitag" to R.string.holiday_de_karfreitag,
        "holiday_de_ostermontag" to R.string.holiday_de_ostermontag,
        "holiday_de_tag_der_arbeit" to R.string.holiday_de_tag_der_arbeit,
        "holiday_de_christi_himmelfahrt" to R.string.holiday_de_christi_himmelfahrt,
        "holiday_de_pfingstmontag" to R.string.holiday_de_pfingstmontag,
        "holiday_de_einheit" to R.string.holiday_de_einheit,
        "holiday_de_weihnachten_1" to R.string.holiday_de_weihnachten_1,
        "holiday_de_weihnachten_2" to R.string.holiday_de_weihnachten_2,
        "holiday_de_dreikoenige" to R.string.holiday_de_dreikoenige,
        "holiday_de_frauentag" to R.string.holiday_de_frauentag,
        "holiday_de_fronleichnam" to R.string.holiday_de_fronleichnam,
        "holiday_de_mariae_himmelfahrt" to R.string.holiday_de_mariae_himmelfahrt,
        "holiday_de_weltkindertag" to R.string.holiday_de_weltkindertag,
        "holiday_de_reformationstag" to R.string.holiday_de_reformationstag,
        "holiday_de_allerheiligen" to R.string.holiday_de_allerheiligen,
        "holiday_de_buss_und_bettag" to R.string.holiday_de_buss_und_bettag,
        "holiday_at_neujahr" to R.string.holiday_at_neujahr,
        "holiday_at_dreikoenige" to R.string.holiday_at_dreikoenige,
        "holiday_at_ostermontag" to R.string.holiday_at_ostermontag,
        "holiday_at_staatsfeiertag" to R.string.holiday_at_staatsfeiertag,
        "holiday_at_himmelfahrt" to R.string.holiday_at_himmelfahrt,
        "holiday_at_pfingstmontag" to R.string.holiday_at_pfingstmontag,
        "holiday_at_fronleichnam" to R.string.holiday_at_fronleichnam,
        "holiday_at_mariae_himmelfahrt" to R.string.holiday_at_mariae_himmelfahrt,
        "holiday_at_nationalfeiertag" to R.string.holiday_at_nationalfeiertag,
        "holiday_at_allerheiligen" to R.string.holiday_at_allerheiligen,
        "holiday_at_mariae_empfaengnis" to R.string.holiday_at_mariae_empfaengnis,
        "holiday_at_christtag" to R.string.holiday_at_christtag,
        "holiday_at_stefanitag" to R.string.holiday_at_stefanitag,
        "holiday_ch_neujahr" to R.string.holiday_ch_neujahr,
        "holiday_ch_karfreitag" to R.string.holiday_ch_karfreitag,
        "holiday_ch_ostermontag" to R.string.holiday_ch_ostermontag,
        "holiday_ch_auffahrt" to R.string.holiday_ch_auffahrt,
        "holiday_ch_pfingstmontag" to R.string.holiday_ch_pfingstmontag,
        "holiday_ch_bundesfeier" to R.string.holiday_ch_bundesfeier,
        "holiday_ch_weihnachten" to R.string.holiday_ch_weihnachten,
        "holiday_ch_stephanstag" to R.string.holiday_ch_stephanstag,
        "holiday_fr_jour_de_lan" to R.string.holiday_fr_jour_de_lan,
        "holiday_fr_lundi_paques" to R.string.holiday_fr_lundi_paques,
        "holiday_fr_fete_du_travail" to R.string.holiday_fr_fete_du_travail,
        "holiday_fr_victoire_1945" to R.string.holiday_fr_victoire_1945,
        "holiday_fr_ascension" to R.string.holiday_fr_ascension,
        "holiday_fr_lundi_pentecote" to R.string.holiday_fr_lundi_pentecote,
        "holiday_fr_fete_nationale" to R.string.holiday_fr_fete_nationale,
        "holiday_fr_assomption" to R.string.holiday_fr_assomption,
        "holiday_fr_toussaint" to R.string.holiday_fr_toussaint,
        "holiday_fr_armistice" to R.string.holiday_fr_armistice,
        "holiday_fr_noel" to R.string.holiday_fr_noel,
        "holiday_it_capodanno" to R.string.holiday_it_capodanno,
        "holiday_it_epifania" to R.string.holiday_it_epifania,
        "holiday_it_pasquetta" to R.string.holiday_it_pasquetta,
        "holiday_it_liberazione" to R.string.holiday_it_liberazione,
        "holiday_it_lavoro" to R.string.holiday_it_lavoro,
        "holiday_it_repubblica" to R.string.holiday_it_repubblica,
        "holiday_it_ferragosto" to R.string.holiday_it_ferragosto,
        "holiday_it_ognissanti" to R.string.holiday_it_ognissanti,
        "holiday_it_immacolata" to R.string.holiday_it_immacolata,
        "holiday_it_natale" to R.string.holiday_it_natale,
        "holiday_it_santo_stefano" to R.string.holiday_it_santo_stefano,
        "holiday_es_ano_nuevo" to R.string.holiday_es_ano_nuevo,
        "holiday_es_reyes" to R.string.holiday_es_reyes,
        "holiday_es_viernes_santo" to R.string.holiday_es_viernes_santo,
        "holiday_es_trabajo" to R.string.holiday_es_trabajo,
        "holiday_es_asuncion" to R.string.holiday_es_asuncion,
        "holiday_es_fiesta_nacional" to R.string.holiday_es_fiesta_nacional,
        "holiday_es_todos_los_santos" to R.string.holiday_es_todos_los_santos,
        "holiday_es_constitucion" to R.string.holiday_es_constitucion,
        "holiday_es_inmaculada" to R.string.holiday_es_inmaculada,
        "holiday_es_navidad" to R.string.holiday_es_navidad,
        "holiday_nl_nieuwjaar" to R.string.holiday_nl_nieuwjaar,
        "holiday_nl_goede_vrijdag" to R.string.holiday_nl_goede_vrijdag,
        "holiday_nl_eerste_paasdag" to R.string.holiday_nl_eerste_paasdag,
        "holiday_nl_tweede_paasdag" to R.string.holiday_nl_tweede_paasdag,
        "holiday_nl_koningsdag" to R.string.holiday_nl_koningsdag,
        "holiday_nl_hemelvaart" to R.string.holiday_nl_hemelvaart,
        "holiday_nl_eerste_pinksterdag" to R.string.holiday_nl_eerste_pinksterdag,
        "holiday_nl_tweede_pinksterdag" to R.string.holiday_nl_tweede_pinksterdag,
        "holiday_nl_eerste_kerstdag" to R.string.holiday_nl_eerste_kerstdag,
        "holiday_nl_tweede_kerstdag" to R.string.holiday_nl_tweede_kerstdag,
        "holiday_pl_nowy_rok" to R.string.holiday_pl_nowy_rok,
        "holiday_pl_trzech_kroli" to R.string.holiday_pl_trzech_kroli,
        "holiday_pl_wielkanoc" to R.string.holiday_pl_wielkanoc,
        "holiday_pl_poniedzialek_wielkanocny" to R.string.holiday_pl_poniedzialek_wielkanocny,
        "holiday_pl_swieto_pracy" to R.string.holiday_pl_swieto_pracy,
        "holiday_pl_konstytucji" to R.string.holiday_pl_konstytucji,
        "holiday_pl_zielone_swiatki" to R.string.holiday_pl_zielone_swiatki,
        "holiday_pl_boze_cialo" to R.string.holiday_pl_boze_cialo,
        "holiday_pl_wniebowziecie" to R.string.holiday_pl_wniebowziecie,
        "holiday_pl_wszystkich_swietych" to R.string.holiday_pl_wszystkich_swietych,
        "holiday_pl_niepodleglosci" to R.string.holiday_pl_niepodleglosci,
        "holiday_pl_boze_narodzenie_1" to R.string.holiday_pl_boze_narodzenie_1,
        "holiday_pl_boze_narodzenie_2" to R.string.holiday_pl_boze_narodzenie_2,
        "holiday_gb_new_year" to R.string.holiday_gb_new_year,
        "holiday_gb_good_friday" to R.string.holiday_gb_good_friday,
        "holiday_gb_easter_monday" to R.string.holiday_gb_easter_monday,
        "holiday_gb_early_may" to R.string.holiday_gb_early_may,
        "holiday_gb_spring_bank" to R.string.holiday_gb_spring_bank,
        "holiday_gb_summer_bank" to R.string.holiday_gb_summer_bank,
        "holiday_gb_christmas" to R.string.holiday_gb_christmas,
        "holiday_gb_boxing_day" to R.string.holiday_gb_boxing_day,
        "holiday_us_new_year" to R.string.holiday_us_new_year,
        "holiday_us_mlk" to R.string.holiday_us_mlk,
        "holiday_us_presidents" to R.string.holiday_us_presidents,
        "holiday_us_memorial" to R.string.holiday_us_memorial,
        "holiday_us_juneteenth" to R.string.holiday_us_juneteenth,
        "holiday_us_independence" to R.string.holiday_us_independence,
        "holiday_us_labor" to R.string.holiday_us_labor,
        "holiday_us_columbus" to R.string.holiday_us_columbus,
        "holiday_us_veterans" to R.string.holiday_us_veterans,
        "holiday_us_thanksgiving" to R.string.holiday_us_thanksgiving,
        "holiday_us_christmas" to R.string.holiday_us_christmas,
        "country_pt" to R.string.country_pt,
        "country_br" to R.string.country_br,
        "holiday_pt_ano_novo" to R.string.holiday_pt_ano_novo,
        "holiday_pt_sexta_feira_santa" to R.string.holiday_pt_sexta_feira_santa,
        "holiday_pt_pascoa" to R.string.holiday_pt_pascoa,
        "holiday_pt_dia_da_liberdade" to R.string.holiday_pt_dia_da_liberdade,
        "holiday_pt_dia_do_trabalhador" to R.string.holiday_pt_dia_do_trabalhador,
        "holiday_pt_corpo_de_deus" to R.string.holiday_pt_corpo_de_deus,
        "holiday_pt_dia_de_portugal" to R.string.holiday_pt_dia_de_portugal,
        "holiday_pt_assuncao" to R.string.holiday_pt_assuncao,
        "holiday_pt_implantacao_republica" to R.string.holiday_pt_implantacao_republica,
        "holiday_pt_todos_os_santos" to R.string.holiday_pt_todos_os_santos,
        "holiday_pt_restauracao_independencia" to R.string.holiday_pt_restauracao_independencia,
        "holiday_pt_imaculada_conceicao" to R.string.holiday_pt_imaculada_conceicao,
        "holiday_pt_natal" to R.string.holiday_pt_natal,
        "holiday_br_confraternizacao" to R.string.holiday_br_confraternizacao,
        "holiday_br_sexta_feira_santa" to R.string.holiday_br_sexta_feira_santa,
        "holiday_br_tiradentes" to R.string.holiday_br_tiradentes,
        "holiday_br_dia_do_trabalho" to R.string.holiday_br_dia_do_trabalho,
        "holiday_br_independencia" to R.string.holiday_br_independencia,
        "holiday_br_aparecida" to R.string.holiday_br_aparecida,
        "holiday_br_finados" to R.string.holiday_br_finados,
        "holiday_br_proclamacao_republica" to R.string.holiday_br_proclamacao_republica,
        "holiday_br_consciencia_negra" to R.string.holiday_br_consciencia_negra,
        "holiday_br_natal" to R.string.holiday_br_natal,
        "holiday_br_carnaval_segunda" to R.string.holiday_br_carnaval_segunda,
        "holiday_br_carnaval_terca" to R.string.holiday_br_carnaval_terca,
        "holiday_br_corpus_christi" to R.string.holiday_br_corpus_christi,
    )

    fun resolve(context: Context, key: String): String =
        byKey[key]?.let { context.getString(it) } ?: key
}
