/*
 * Mushotoku — a privacy-focused, offline productivity app.
 * Copyright (C) 2026 Tom Frischmuth
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.mushotoku.app.ui

import java.time.LocalDate

object BuddhistQuotes {

    fun today(isGerman: Boolean): String {
        val list = if (isGerman) de else en
        val idx = (LocalDate.now().dayOfYear - 1) % list.size
        return list[idx]
    }

    private val de = listOf(
        "Der gegenwärtige Augenblick ist unser wahres Zuhause.",
        "Jeder Atemzug ist eine Einladung, neu zu beginnen.",
        "Mitgefühl beginnt damit, sich selbst freundlich zu begegnen.",
        "Was du heute bist, entsteht aus deinen heutigen Gedanken.",
        "Lass los, was du nicht mehr tragen kannst.",
        "Im Stillen findet der Geist zu sich selbst zurück.",
        "Jeder Moment des Bewusstseins ist ein kostbares Geschenk.",
        "Der Weg beginnt nicht irgendwo — er beginnt hier, jetzt.",
        "Freude entsteht nicht durch Sammeln, sondern durch Loslassen.",
        "Selbst ein kleines Licht vertreibt große Dunkelheit.",
        "Wer sich selbst kennt, findet überall Frieden.",
        "Das Leiden endet dort, wo das Festhalten endet.",
        "Behandle jeden Menschen wie einen alten Freund.",
        "Ein liebevolles Herz ist das größte Geschenk.",
        "Geduld ist der Weg durch alle Schwierigkeiten.",
        "Was du im Geist aussäst, ernte du in der Welt.",
        "Stille ist keine Abwesenheit — sie ist Anwesenheit.",
        "Der Geist ist wie der Himmel: unberührt von dem, was durch ihn zieht.",
        "Erwachen bedeutet, zu sehen, wie die Dinge wirklich sind.",
        "Jeder Schritt auf dem Weg ist der Weg.",
        "Das Hier und Jetzt zu bewohnen ist die tiefste Praxis.",
        "Mitgefühl ist die Antwort auf fast jede Frage.",
        "Vertraue deiner eigenen inneren Stille.",
        "Nichts ist für immer — und das ist eine Befreiung.",
        "Der Fluss fließt nicht gegen sich selbst.",
        "Freundlichkeit kostet nichts und gibt alles.",
        "Wer den Augenblick umarmt, dem entgeht kein Leben.",
        "Auch dies wird vergehen.",
        "Das Herz, das loslässt, wird leicht.",
        "Sei sanft zu dir selbst — du bist ein Kind des Universums.",
        "Bewusstsein ist das Licht, das alles erhellt.",
        "Ein ruhiger Geist sieht mehr als ein geschäftiger.",
        "Was zählt, ist nicht wie lang, sondern wie tief du gelebt hast.",
        "Ehrlichkeit mit sich selbst ist der Anfang aller Weisheit.",
        "Wenn du still wirst, hörst du, was wirklich wichtig ist.",
        "Das Loslassen ist oft der mutigste Akt.",
        "Verbinde dich mit dem, was lebendig ist — in dir und um dich.",
        "Angst ist nur ein Gedanke, der Erlaubnis braucht.",
        "Die Natur lehrt uns täglich das Loslassen.",
        "Wer im Inneren sucht, findet das Äußere weniger dringend.",
        "Jeder Moment trägt den Keim der Erneuerung.",
        "Frieden ist kein Ziel — er ist eine Art zu gehen.",
        "Das Leiden des einen geht uns alle an.",
        "Aus Stille entsteht das tiefste Hören.",
        "Sei wie das Wasser: fließend, anpassungsfähig, beharrlich.",
        "Das Herz hat Räume, die nur die Stille öffnet.",
        "Das Unwichtige loszulassen schafft Raum für das Wesentliche.",
        "Jede Sekunde Präsenz ist kostbarer als Stunden des Nachsinnens.",
        "Was du widerstehst, bleibt — was du anerkennst, löst sich.",
        "Der gegenwärtige Moment hat immer genug.",
        "Freude ist ein innerer Zustand, kein äußerer Besitz.",
        "Atme tief — das Leben fließt von selbst.",
        "Kein Weg ist zu lang für den, der schon angekommen ist.",
        "Das Selbst ist stiller als die Stille zwischen Herzschlägen.",
        "Mitgefühl ohne Weisheit verbrennt sich selbst aus.",
        "Weisheit ohne Mitgefühl ist kalt und leer.",
        "Beobachte deine Gedanken, als wären sie Wolken im Himmel.",
        "Du bist der Himmel, nicht das Wetter.",
        "Nichts ist dauerhaft — selbst der härteste Schmerz verändert sich.",
        "Gleichmut ist nicht Gleichgültigkeit, sondern tiefes Vertrauen.",
        "Wer in der Stille übt, trägt sie in den Lärm.",
        "Das Gute zu sehen ist eine Übung, die das Herz öffnet.",
        "Die tiefste Form der Liebe ist die Liebe ohne Erwartung.",
        "Jeder Sonnenaufgang ist eine zweite Chance.",
        "Wenn du gehst, geh nur. Wenn du sitzt, sitz nur.",
        "Das Geheimnis des Lebens liegt in seiner Vergänglichkeit.",
        "Was du heute loslässt, trägt dich morgen leichter.",
        "Gib dem, was du liebst, Raum zu atmen.",
        "Jedes Mal, wenn du den Atem bemerkst, kommst du nach Hause.",
        "Die Praxis ist nicht das Ausschalten des Geistes, sondern sein freundliches Beobachten.",
        "Erleuchtung ist nicht Flucht aus dem Leben, sondern tiefes Eintauchen.",
        "Was wirklich zählt, zeigt sich immer in der Stille.",
        "Der Baum beugt sich im Sturm und bricht nicht — sei wie der Baum.",
        "Achtsamkeit ist das Gegenmittel gegen alle Hast.",
        "Behalte einen ruhigen Atem, und du behältst einen ruhigen Geist.",
        "Das Wahre versteckt sich nicht — es wartet nur auf Aufmerksamkeit.",
        "Alles, was entsteht, vergeht auch — das ist keine Tragödie, das ist das Leben.",
        "Halte dein Herz offen für das, was kommt.",
        "Ein Geist ohne Urteile sieht klarer.",
        "Schmerz ist unvermeidlich, Leiden eine Wahl.",
        "Was immer kommt, empfange es mit offenem Herzen.",
        "Die Wurzeln der Freude wachsen in der Praxis der Achtsamkeit.",
        "Liebe dich selbst so, wie du einen guten alten Freund liebst.",
        "Das, was du suchst, sucht dich auch.",
        "Glaube nicht jedem Gedanken — sie sind nicht alle wahr.",
        "Vollkommene Leere bedeutet vollkommene Möglichkeit.",
        "Das Licht ist schon da — du musst nur die Augen öffnen.",
        "Trauer zu fühlen bedeutet, geliebt zu haben — das ist Reichtum.",
        "Jedes Lebewesen sehnt sich nach Glück — erkenne das, und du erkennst dich in allen.",
        "Der stille Zeuge in dir ist unverletzt und unverlierbar.",
        "Das Herz weiß oft, was der Geist noch nicht sieht.",
        "Der erste Schritt des Erwachens ist das Erkennen des Schlafs.",
        "Sei gütig zu allen Wesen — sie tragen ihre eigenen Kämpfe.",
        "Ein offenes Herz ist stärker als ein gepanzertes.",
        "Das, was Energie bekommt, wächst — richte sie weise aus.",
        "Dankbarkeit ist die schnellste Brücke zwischen Mangel und Fülle.",
        "Wer im Frieden mit sich ist, macht Frieden mit der Welt.",
        "Der Geist, der loslässt, wird zu einem See ohne Wellen.",
        "Jede Meditation pflanzt eine Wurzel des Friedens.",
        "Tue das Gute, weil es gut ist, nicht wegen der Belohnung.",
        "Betrachte dein Leben mit der Sanftheit eines Lehrers.",
        "Schwierigkeit ist die Schule, in der Weisheit geboren wird.",
        "Der Geist, der nicht urteilt, ruht.",
        "Das Leben ist kostbar — lebe es mit Sorgfalt.",
        "Jeder Atemzug verbindet dich mit allem Lebendigen.",
        "Atme und erkenne: Du bist lebendig, und das ist genug.",
        "Das Leichte entsteht im Üben, nicht im Nachdenken.",
        "Jeder Tag ist ein neuer Anfang für den, der bereit ist zu beginnen.",
        "Was du mit Achtsamkeit tust, wird zur Meditation.",
        "Das Herz braucht keine Erklärungen, nur Stille.",
        "Führe ein Leben, auf das dein späteres Selbst zurückblickt und lächelt.",
        "Der Wind weht ohne Anstrengung — sei wie der Wind.",
        "Dein Mitgefühl ist die Welt, die heilt.",
        "Liebe als Praxis bedeutet: täglich, in kleinen Dingen.",
        "Was du gibst, kommt verändert zurück.",
        "Jeder Moment der Güte hinterlässt eine bleibende Spur.",
        "Das Loslassen des Ich ist der Anfang aller Freiheit.",
        "Wenn der Geist still wird, spricht das Herz.",
        "Die Frage «Wer bin ich?» ist die heilsamste aller Fragen.",
        "Sitz, und lass das Universum zu dir sprechen.",
        "Der beste Weg, die Zukunft zu ehren, ist, die Gegenwart zu leben.",
        "Nichts entsteht aus sich selbst — alles ist verbunden.",
        "Du bist nicht deine Gedanken. Du bist derjenige, der sie bemerkt.",
        "Die Stille zwischen zwei Gedanken ist dein ursprüngliches Zuhause.",
        "Wenn das Herz weich wird, öffnet sich die Welt.",
        "Vergebung ist nicht für den anderen — sie ist für dich.",
        "Was du vergibst, hältst du nicht mehr gefangen.",
        "Sei sanft mit dir in schwierigen Zeiten — das ist keine Schwäche.",
        "Die Lotusblüte wächst durch den Schlamm — so auch die Weisheit.",
        "Du kannst das Meer nicht beruhigen, aber du kannst lernen, auf den Wellen zu reiten.",
        "Ein Lächeln kostet nichts und gibt viel.",
        "Wende dein Gesicht zur Sonne — dann liegt der Schatten hinter dir.",
        "Was in dir ist, spiegelt sich in der Welt.",
        "Der Augenblick ist vollständig — ihm fehlt nichts.",
        "Lass den Hunger nach Stille sein Nahrung finden.",
        "Achte auf die kleinen Freuden — sie tragen die Welt.",
        "Freundlichkeit ist eine Sprache, die jeder versteht.",
        "Das Mitgefühl öffnet das Herz wie Wasser den Stein.",
        "Verbinde dich täglich mit der Erde unter deinen Füßen.",
        "Das Atmen ist die erste und letzte Praxis.",
        "Alles verändert sich. Vertraue dem Wandel.",
        "Das Netz des Lebens trägt uns alle — niemand fällt heraus.",
        "Was immer du tust, tue es mit ganzem Herzen.",
        "Der innere Friede ist unerschütterlich, wenn er tief genug verwurzelt ist.",
        "Halte inne — das Leben wartet nicht auf Eile.",
        "Was du in der Stille lernst, trägst du in die Welt.",
        "Sei die Güte, die du sehen möchtest.",
        "Kein Gedanke ist so wichtig, dass er deinen Frieden stören müsste.",
        "Lebe so, dass jeder Schritt eine Berührung mit dem Heiligen ist.",
        "Das Heilige versteckt sich nirgends — es ist überall.",
        "Sprich wenig, höre viel, sei ganz da.",
        "Das Gute ist immer möglich — auch jetzt, auch hier.",
        "Frieden ist die tiefste Form des Mutes.",
        "Wer Frieden in sich trägt, streut ihn überall.",
        "Das Aufwachen beginnt im kleinen Ding: dem nächsten Atemzug.",
        "Alles Leiden entsteht aus dem Greifen.",
        "Alles Glück entsteht aus dem Loslassen.",
        "Ein Herz voller Liebe sieht überall ein Wunder.",
        "Dein ursprüngliches Gesicht — das Gesicht vor allen Gedanken.",
        "Das Schweigen ist die Muttersprache der Seele.",
        "Kein Sturm dauert ewig — auch der innere nicht.",
        "Gedanken kommen und gehen wie Gäste. Du bist das Haus.",
        "Das Leben ist zu kostbar, um im Autopiloten zu leben.",
        "Sei neugierig auf den Augenblick, nicht ängstlich vor ihm.",
        "Jedes Aufatmen ist ein kleines Auferstehen.",
        "Der Weg der Mitte ist oft der schwierigste — und der heilsamste.",
        "Hass erzeugt Hass. Güte erzeugt Güte. Wähle sorgfältig.",
        "Alles, was du wirklich brauchst, ist bereits in dir.",
        "Wenn du nicht weißt, was du tun sollst, atme erst einmal.",
        "Die größte Reise ist die Reise nach innen.",
        "Das Ego lärmt, das Selbst ist still.",
        "Lerne, in der Mitte des Chaos still zu sein.",
        "Was sich im Inneren klärt, zeigt sich im Äußeren.",
        "Das Beste, was du geben kannst, ist deine vollständige Anwesenheit.",
        "Jede Tat des Mitgefühls ist eine Tat der Weisheit.",
        "Das Glück liegt nicht am Ende des Weges — es ist der Weg.",
        "Lass den Geist wie den Himmel sein: offen, weit, ungebunden.",
        "Wer das Jetzt annimmt, hat genug.",
        "Jeder Herzschlag ist ein Geschenk, nicht ein Selbstverständnis.",
        "Wenn das Denken anhält, beginnt die Weisheit.",
        "Der Mut zu sein, wer man ist, ist die erste Form der Freiheit.",
        "Sei wachsam, ohne zu urteilen.",
        "Erkenne das Leiden als Lehrer, nicht als Feind.",
        "Der Atem verbindet dich mit dem, was immer schon da war.",
        "Zwischen Reiz und Reaktion liegt ein Raum — dort liegt deine Freiheit.",
        "Wer täglich etwas loslässt, wird täglich freier.",
        "Das Herz, das dankbar ist, leidet seltener.",
        "Jede Schwierigkeit ist eine Einladung zur Reife.",
        "Tue das Nächste, was liebevoll ist.",
        "Das Mysterium des Lebens liegt nicht hinter ihm, sondern mitten drin.",
        "Halte die Welt mit leichten Händen.",
        "Festhalten ist das Gegenteil von Lieben.",
        "Wer anderen Frieden gibt, findet selbst Frieden.",
        "Die wahre Heimat ist im gegenwärtigen Augenblick.",
        "Das Herz öffnet sich dort, wo die Kontrolle endet.",
        "Jede Form des Leidens enthält eine Einladung zum Wachsen.",
        "Bewusstsein ist der Raum, in dem alles erscheint und vergeht.",
        "Ruhe ist kein Luxus — sie ist eine Notwendigkeit der Seele.",
        "Das Vergangene loszulassen bedeutet nicht, es zu vergessen — es bedeutet, es nicht länger als Gefängnis zu tragen.",
        "Wenn der Geist sich entleert, füllst du dich mit dem, was wesentlich ist.",
        "Das Tiefste im Menschen ist still.",
        "Dankbarkeit öffnet das Herz. Ärger schließt es.",
        "Das Einfache ist oft das Tiefste.",
        "Jede Geste der Güte pflanzt einen Samen des Friedens.",
        "Was du nicht kontrollieren kannst, darfst du loslassen.",
        "Wer loslässt, verliert nicht — er gewinnt Freiheit.",
        "Der Geist ist unruhig von Natur aus — lass ihn zur Ruhe kommen.",
        "Das Wasser findet immer seinen Weg — auch du findest deinen.",
        "Das Leben lebt durch uns, nicht für uns.",
        "Sei das Licht, das andere sehen können.",
        "Stärke wächst dort, wo Weichheit ist.",
        "Alles hat seine Zeit. Auch das Heilen.",
        "Das Schweigen zweier Menschen, die sich wirklich kennen, ist Liebe.",
        "Was zählt, ist die Qualität deiner Gegenwart.",
        "Jeder Mensch kämpft einen Kampf, den du nicht kennst — sei deshalb gütig.",
        "Der Weg zur inneren Freiheit beginnt mit dem Erkennen des Käfigs.",
        "Was du annimmst, verliert seine Macht über dich.",
        "Das Leben fragt uns täglich, was wir ihm geben.",
        "In der Stille liegt keine Leere, sondern das Volle.",
        "Das Herz hat immer Raum für noch mehr Mitgefühl.",
        "Wachstum braucht keine Eile — auch der Baum wächst langsam.",
        "Du bist nicht kaputt. Du bist mitten im Wachsen.",
        "Sei geduldig mit allem, was in dir ungelöst ist.",
        "Die Vergangenheit liegt hinter dir, die Zukunft vor dir. Du bist hier.",
        "Das Jetzt zu bewohnen ist das Mutigste, was ein Mensch tun kann.",
        "Werde stiller als deine Gedanken.",
        "Was auch immer du heute tust — tue es mit Bewusstsein.",
        "Dein Herz ist großzügiger als dein Verstand.",
        "Vertraue dem Prozess. Vertraue dem Leben. Vertraue dir.",
        "Mitgefühl ist kein Gefühl — es ist eine Entscheidung.",
        "Jeden Tag kannst du von vorne anfangen.",
        "Wer in sich selbst Zuflucht findet, braucht nichts Äußeres.",
        "Nicht Vollkommenheit, sondern Aufrichtigkeit ist das Ziel.",
        "Wenn du im Dunkeln bist, warte. Das Licht kommt.",
        "Das Meditieren trainiert den Geist, das Herz zu öffnen.",
        "Lebe in dem, was ist — nicht in dem, was sein sollte.",
        "Das Hier und Jetzt annehmen ist die tiefste Form des Ja-Sagens.",
        "Jedes Wesen verdient Mitgefühl — auch das schwierigste.",
        "Das Herz, das verzeiht, atmet freier.",
        "Wandlung beginnt immer in der Stille.",
        "Auch du bist Teil des großen Netzes des Lebens.",
        "Das Heilige ist nicht getrennt vom Alltäglichen.",
        "Jede Tasse Tee, achtsam getrunken, ist eine Meditation.",
        "Jeder Schritt, bewusst getan, ist ein Schritt im Erwachen.",
        "Was du mit Liebe tust, überdauert dich.",
        "Ein reines Herz sieht überall das Wunder.",
        "Verankere dich im Atem, wenn alles um dich schwankt.",
        "Halte beides: das Wunder und den Schmerz.",
        "Das Aushalten des Unbekannten ist eine spirituelle Übung.",
        "Jedes Mal, wenn du aufhörst zu kämpfen und einfach da bist, wirst du frei.",
        "Das Leben braucht deine vollständige Hingabe, nicht deine Perfektion.",
        "Wer sich selbst kennt, erschrickt weniger vor dem Leben.",
        "Der Geist ist wie ein Spiegel: er zeigt, was ihm gezeigt wird — halte ihn sauber.",
        "Was du regelmäßig übst, wird zu dem, was du bist.",
        "Das Erwachen ist kein Ziel, sondern ein Aufwachen.",
        "Jede Minute Stille ist eine Minute Klarheit.",
        "Freude ist der natürliche Zustand eines ruhigen Herzens.",
        "Das Herz weiß mehr als tausend Bücher sagen können.",
        "Manchmal ist Nichtstun die tiefste Form der Weisheit.",
        "Lass das Leben dich berühren — das ist der Sinn des Fühlens.",
        "Jede Emotion, die du bezeugst, verliert ihren Stachel.",
        "Was du ignorierst, wächst. Was du anschaust, verändert sich.",
        "Der Atem hört nie auf — er ist immer ein Anker in der Gegenwart.",
        "Kehre immer zum Atem zurück. Er wartet auf dich.",
        "Das Ewige ist nicht weit weg — es atmet in dir.",
        "Was immer passiert, dein Wesen ist unverletzbar.",
        "Gedanken sind keine Tatsachen. Erkenne das und werde freier.",
        "Das Mitgefühl, das du dir selbst gibst, gibst du auch der Welt.",
        "Der beste Augenblick zum Üben ist immer dieser hier.",
        "Die stillste Stunde des Tages gehört dir.",
        "Ein Mensch im Frieden ist ein Geschenk an alle.",
        "Frieden ist keine Abwesenheit von Schwierigkeit, sondern ein Gleichgewicht inmitten davon.",
        "Das Üben ist nicht das Ziel — das Üben ist das Leben.",
        "Was du annimmst, muss dich nicht mehr verfolgen.",
        "Der Weg des Herzens ist immer der direkteste.",
        "Verankere dich täglich in dem, was dir wirklich wichtig ist.",
        "Erwache in dir das, was schon immer erwacht war.",
        "Stille ist keine Schwäche. Sie ist Kraft, die sich nicht verausgabt.",
        "Was du täglich nährst, wächst. Nähre das Gute in dir.",
        "Das Leben fragt uns nach unserer Bereitschaft, nicht nach unserer Perfektion.",
        "Der Augenblick ist vollständig — auch wenn du es noch nicht siehst.",
        "Setz dich hin, atme, und lass den Sturm vorbeiziehen.",
        "Das tiefe Hören öffnet das Herz wie kein anderes Werkzeug.",
        "Erwache: Nicht irgendwann, sondern jetzt.",
        "Jede Meditation ist eine Heimkehr.",
        "Auch ein kurzer Moment der Stille ist wertvoll.",
        "Das Wasser wird nicht sauber durch Kämpfen, sondern durch Ruhe.",
        "Der Geist, der lernt, wird der Geist, der wächst.",
        "Was du heute stillst, erwacht morgen als Klarheit.",
        "Das Leben ist kurz — das macht es wertvoll, nicht wertlos.",
        "Jeder Atemzug ist ein kleines Ja zum Leben.",
        "Ja sagen zum gegenwärtigen Augenblick ist die tiefste Praxis.",
        "Das Herz hat seine eigene Weisheit — höre ihr zu.",
        "Jede Tat der Güte hellt die Welt ein kleines bisschen auf.",
        "Du hast mehr Einfluss, als du denkst — durch das, was du ausstrahlst.",
        "Was wesentlich ist, zeigt sich, wenn das Unwesentliche fortgeht.",
        "Der Friede, den du in dir pflegst, breitet sich aus.",
        "Atme tief und erkenne: Alles ist wie es ist.",
        "Das Annehmen macht stärker, nicht schwächer.",
        "Jede Wunde birgt eine Botschaft, wenn wir still genug sind, sie zu hören.",
        "Das Licht ist immer da — auch hinter den Wolken.",
        "Vertraue darauf: Der Himmel ist immer blau, auch wenn er bedeckt ist.",
        "Du bist tiefer als alle deine Gedanken und Gefühle.",
        "Erkenne deine Tiefe — und ruhe dort.",
        "Jeder, der atmet, hat die Möglichkeit zu erwachen.",
        "Das Erwachen braucht keine Erlaubnis — nur Bereitschaft.",
        "Freundlichkeit dir selbst gegenüber ist die Voraussetzung für Freundlichkeit gegenüber anderen.",
        "Was du innerlich pflegst, bringst du in die Welt.",
        "Das Universum ist in jedem Atemzug enthalten.",
        "Der heutige Tag ist einmalig — er wird nie wiederkehren.",
        "Lebe ihn, als wäre er das Geschenk, das er ist.",
        "Was auch immer heute kommt, du kannst ihm begegnen.",
        "Du bist ausgestattet für diesen Moment.",
        "Der Weg endet nie — er öffnet sich immer neu."
    )

    private val en = listOf(
        "The present moment is our true home.",
        "Every breath is an invitation to begin again.",
        "Compassion starts with being kind to yourself.",
        "What you are today grows from today's thoughts.",
        "Let go of what you can no longer carry.",
        "In stillness, the mind returns to itself.",
        "Every moment of awareness is a precious gift.",
        "The path does not begin somewhere far away — it begins here, now.",
        "Joy arises not from collecting, but from letting go.",
        "Even a small light dispels great darkness.",
        "One who knows themselves finds peace everywhere.",
        "Suffering ends where clinging ends.",
        "Treat every person as an old friend.",
        "A loving heart is the greatest gift.",
        "Patience is the path through all difficulties.",
        "What you sow in the mind, you reap in the world.",
        "Silence is not an absence — it is a presence.",
        "The mind is like the sky, untouched by what passes through it.",
        "Awakening means seeing things as they truly are.",
        "Every step on the path is the path.",
        "To dwell in the here and now is the deepest practice.",
        "Compassion is the answer to almost every question.",
        "Trust your own inner silence.",
        "Nothing lasts forever — and that is a liberation.",
        "The river does not flow against itself.",
        "Kindness costs nothing and gives everything.",
        "One who embraces each moment misses no life.",
        "This too shall pass.",
        "The heart that lets go becomes light.",
        "Be gentle with yourself — you are a child of the universe.",
        "Awareness is the light that illuminates everything.",
        "A quiet mind sees more than a busy one.",
        "What counts is not how long, but how deeply you have lived.",
        "Honesty with oneself is the beginning of all wisdom.",
        "When you grow still, you hear what truly matters.",
        "Letting go is often the bravest act.",
        "Connect with what is alive — in you and around you.",
        "Fear is only a thought that has been given permission.",
        "Nature teaches us daily the art of letting go.",
        "Those who seek within find the outer world less urgent.",
        "Every moment carries the seed of renewal.",
        "Peace is not a destination — it is a way of walking.",
        "The suffering of one concerns us all.",
        "From stillness comes the deepest listening.",
        "Be like water: flowing, adaptable, persistent.",
        "The heart has rooms that only silence can open.",
        "Releasing the unimportant creates space for the essential.",
        "A second of presence is worth more than hours of rumination.",
        "What you resist remains — what you acknowledge dissolves.",
        "The present moment always has enough.",
        "Joy is an inner state, not an outer possession.",
        "Breathe deeply — life flows by itself.",
        "No path is too long for one who has already arrived.",
        "The self is quieter than the silence between heartbeats.",
        "Compassion without wisdom burns itself out.",
        "Wisdom without compassion is cold and empty.",
        "Observe your thoughts as if they were clouds in the sky.",
        "You are the sky, not the weather.",
        "Nothing is permanent — even the hardest pain changes.",
        "Equanimity is not indifference, but deep trust.",
        "Those who practice in stillness carry it into the noise.",
        "Seeing the good is a practice that opens the heart.",
        "The deepest form of love is love without expectation.",
        "Every sunrise is a second chance.",
        "When you walk, just walk. When you sit, just sit.",
        "The secret of life lies in its impermanence.",
        "What you release today carries you more lightly tomorrow.",
        "Give what you love room to breathe.",
        "Every time you notice your breath, you come home.",
        "Practice is not switching off the mind but observing it with kindness.",
        "Enlightenment is not escape from life but deep immersion in it.",
        "What truly matters always reveals itself in silence.",
        "The tree bends in the storm and does not break — be like the tree.",
        "Mindfulness is the antidote to all haste.",
        "Keep a calm breath and you keep a calm mind.",
        "The true does not hide — it only waits for attention.",
        "All that arises also passes — that is not tragedy, that is life.",
        "Keep your heart open to what comes.",
        "A mind without judgment sees more clearly.",
        "Pain is inevitable; suffering is a choice.",
        "Whatever comes, receive it with an open heart.",
        "The roots of joy grow in the practice of mindfulness.",
        "Love yourself as you would love a dear old friend.",
        "What you seek is also seeking you.",
        "Do not believe every thought — not all of them are true.",
        "Perfect emptiness means perfect possibility.",
        "The light is already there — you only need to open your eyes.",
        "To feel grief means to have loved — that is wealth.",
        "Every being longs for happiness — recognise that and you see yourself in all.",
        "The silent witness within you is unhurt and indestructible.",
        "The heart often knows what the mind has not yet seen.",
        "The first step of awakening is recognising the sleep.",
        "Be kind to all beings — they carry their own battles.",
        "An open heart is stronger than an armoured one.",
        "What receives energy grows — direct it wisely.",
        "Gratitude is the fastest bridge between lack and abundance.",
        "One at peace with themselves makes peace with the world.",
        "The mind that lets go becomes a lake without waves.",
        "Every meditation plants a root of peace.",
        "Do good because it is good, not for the reward.",
        "Look at your life with the gentleness of a teacher.",
        "Difficulty is the school in which wisdom is born.",
        "The mind that does not judge rests.",
        "Life is precious — live it with care.",
        "Every breath connects you with all living things.",
        "Breathe and know: you are alive, and that is enough.",
        "Ease arises from practice, not from thinking.",
        "Every day is a new beginning for one ready to begin.",
        "What you do with mindfulness becomes meditation.",
        "The heart needs no explanations, only silence.",
        "Live a life your future self looks back on and smiles.",
        "The wind blows without effort — be like the wind.",
        "Your compassion is the world that heals.",
        "Love as practice means: daily, in small things.",
        "What you give returns transformed.",
        "Every moment of kindness leaves a lasting trace.",
        "Releasing the self is the beginning of all freedom.",
        "When the mind grows still, the heart speaks.",
        "The question 'Who am I?' is the most healing of all questions.",
        "Sit, and let the universe speak to you.",
        "The best way to honour the future is to live the present.",
        "Nothing arises from itself — everything is connected.",
        "You are not your thoughts. You are the one who notices them.",
        "The silence between two thoughts is your original home.",
        "When the heart softens, the world opens.",
        "Forgiveness is not for the other — it is for you.",
        "What you forgive no longer holds you captive.",
        "Be gentle with yourself in difficult times — that is not weakness.",
        "The lotus grows through mud — so too does wisdom.",
        "You cannot calm the sea, but you can learn to ride the waves.",
        "A smile costs nothing and gives much.",
        "Turn your face toward the sun — then the shadow falls behind you.",
        "What is within you is reflected in the world.",
        "The moment is complete — it lacks nothing.",
        "Let the hunger for stillness find its nourishment.",
        "Notice the small joys — they carry the world.",
        "Kindness is a language everyone understands.",
        "Compassion opens the heart the way water opens stone.",
        "Connect daily with the earth beneath your feet.",
        "Breathing is the first and the last practice.",
        "Everything changes. Trust the change.",
        "The web of life holds us all — no one falls through.",
        "Whatever you do, do it with your whole heart.",
        "Inner peace is unshakeable when it is rooted deeply enough.",
        "Pause — life does not wait for haste.",
        "What you learn in silence you carry into the world.",
        "Be the kindness you wish to see.",
        "No thought is important enough to disturb your peace.",
        "Live so that every step is a touch of the sacred.",
        "The sacred hides nowhere — it is everywhere.",
        "Speak little, listen much, be fully present.",
        "The good is always possible — even now, even here.",
        "Peace is the deepest form of courage.",
        "One who carries peace within scatters it everywhere.",
        "Awakening begins in the small thing: the next breath.",
        "All suffering arises from grasping.",
        "All happiness arises from letting go.",
        "A heart full of love sees a miracle everywhere.",
        "Your original face — the face before all thought.",
        "Silence is the mother tongue of the soul.",
        "No storm lasts forever — not even the inner one.",
        "Thoughts come and go like guests. You are the house.",
        "Life is too precious to live on autopilot.",
        "Be curious about the moment, not afraid of it.",
        "Every exhale is a small resurrection.",
        "The middle way is often the hardest — and the most healing.",
        "Hatred breeds hatred. Kindness breeds kindness. Choose carefully.",
        "Everything you truly need is already within you.",
        "When you do not know what to do, first breathe.",
        "The greatest journey is the journey inward.",
        "The ego is noisy; the self is still.",
        "Learn to be still in the midst of chaos.",
        "What clarifies within shows itself without.",
        "The best thing you can give is your complete presence.",
        "Every act of compassion is an act of wisdom.",
        "Happiness is not at the end of the path — it is the path.",
        "Let the mind be like the sky: open, vast, unbound.",
        "One who accepts the now has enough.",
        "Every heartbeat is a gift, not a given.",
        "When thinking stops, wisdom begins.",
        "The courage to be who you are is the first form of freedom.",
        "Be watchful, without judging.",
        "Recognise suffering as a teacher, not an enemy.",
        "The breath connects you with what was always already there.",
        "Between stimulus and response there is a space — there lies your freedom.",
        "One who releases something daily becomes freer daily.",
        "The grateful heart suffers less.",
        "Every difficulty is an invitation to maturity.",
        "Do the next loving thing.",
        "The mystery of life is not behind it, but in the middle of it.",
        "Hold the world with light hands.",
        "Clinging is the opposite of loving.",
        "One who gives others peace finds peace themselves.",
        "The true home is in the present moment.",
        "The heart opens where control ends.",
        "Every form of suffering holds an invitation to grow.",
        "Awareness is the space in which everything appears and passes.",
        "Rest is not a luxury — it is a necessity of the soul.",
        "Releasing the past does not mean forgetting it — it means no longer carrying it as a prison.",
        "When the mind empties, you fill with what is essential.",
        "The deepest thing in a person is still.",
        "Gratitude opens the heart. Anger closes it.",
        "The simple is often the deepest.",
        "Every gesture of kindness plants a seed of peace.",
        "What you cannot control, you may release.",
        "One who lets go does not lose — they gain freedom.",
        "The mind is restless by nature — allow it to come to rest.",
        "Water always finds its way — so will you.",
        "Life lives through us, not for us.",
        "Be the light that others can see.",
        "Strength grows where there is softness.",
        "Everything has its time. Including healing.",
        "The silence between two people who truly know each other is love.",
        "What counts is the quality of your presence.",
        "Every person fights a battle you know nothing of — be kind.",
        "The path to inner freedom begins by recognising the cage.",
        "What you accept loses its power over you.",
        "Life asks us daily what we will give it.",
        "In stillness there is no emptiness, but fullness.",
        "The heart always has room for more compassion.",
        "Growth needs no haste — even the tree grows slowly.",
        "You are not broken. You are in the middle of growing.",
        "Be patient with everything unresolved within you.",
        "The past is behind you, the future before you. You are here.",
        "To inhabit the now is the bravest thing a person can do.",
        "Become quieter than your thoughts.",
        "Whatever you do today — do it with awareness.",
        "Your heart is more generous than your mind.",
        "Trust the process. Trust life. Trust yourself.",
        "Compassion is not a feeling — it is a choice.",
        "Every day you can begin again.",
        "One who takes refuge within needs nothing from outside.",
        "Not perfection but sincerity is the goal.",
        "When you are in darkness, wait. The light comes.",
        "Meditation trains the mind to open the heart.",
        "Live in what is — not in what should be.",
        "Accepting the here and now is the deepest form of saying yes.",
        "Every being deserves compassion — even the most difficult.",
        "The heart that forgives breathes more freely.",
        "Transformation always begins in silence.",
        "You too are part of the great web of life.",
        "The sacred is not separate from the everyday.",
        "Every cup of tea, drunk mindfully, is a meditation.",
        "Every step, taken consciously, is a step in awakening.",
        "What you do with love outlasts you.",
        "A pure heart sees wonder everywhere.",
        "Anchor yourself in the breath when everything around you wavers.",
        "Hold both: the wonder and the pain.",
        "Tolerating the unknown is a spiritual practice.",
        "Every time you stop fighting and simply are, you become free.",
        "Life needs your complete surrender, not your perfection.",
        "One who knows themselves is less startled by life.",
        "The mind is like a mirror — it shows what is shown to it. Keep it clear.",
        "What you practise regularly becomes what you are.",
        "Awakening is not a destination but a waking up.",
        "Every minute of silence is a minute of clarity.",
        "Joy is the natural state of a quiet heart.",
        "The heart knows more than a thousand books can say.",
        "Sometimes doing nothing is the deepest form of wisdom.",
        "Let life touch you — that is the purpose of feeling.",
        "Every emotion you witness loses its sting.",
        "What you ignore grows. What you look at changes.",
        "The breath never stops — it is always an anchor in the present.",
        "Always return to the breath. It is waiting for you.",
        "The eternal is not far away — it breathes within you.",
        "Whatever happens, your essence is inviolable.",
        "Thoughts are not facts. Recognise that and become freer.",
        "The compassion you give yourself, you give to the world.",
        "The best moment to practise is always this one here.",
        "The quietest hour of the day belongs to you.",
        "A person at peace is a gift to everyone.",
        "Peace is not the absence of difficulty but balance in the midst of it.",
        "Practice is not the goal — practice is life.",
        "What you accept no longer needs to pursue you.",
        "The path of the heart is always the most direct.",
        "Anchor yourself daily in what truly matters to you.",
        "Awaken in yourself what was always already awake.",
        "Silence is not weakness. It is strength that does not exhaust itself.",
        "What you nourish daily grows. Nourish the good in you.",
        "Life asks for our readiness, not our perfection.",
        "The moment is complete — even if you cannot yet see it.",
        "Sit down, breathe, and let the storm pass.",
        "Deep listening opens the heart like no other tool.",
        "Awaken: not someday, but now.",
        "Every meditation is a homecoming.",
        "Even a brief moment of stillness is precious.",
        "Water is not cleansed by fighting but by resting.",
        "The mind that learns is the mind that grows.",
        "What you still today awakens tomorrow as clarity.",
        "Life is short — that makes it precious, not worthless.",
        "Every breath is a small yes to life.",
        "Saying yes to the present moment is the deepest practice.",
        "The heart has its own wisdom — listen to it.",
        "Every act of kindness brightens the world a little.",
        "You have more influence than you think — through what you radiate.",
        "What is essential shows itself when the inessential falls away.",
        "The peace you cultivate within you spreads outward.",
        "Breathe deeply and recognise: everything is as it is.",
        "Acceptance makes us stronger, not weaker.",
        "Every wound holds a message if we are still enough to hear it.",
        "The light is always there — even behind the clouds.",
        "Trust this: the sky is always blue, even when it is overcast.",
        "You are deeper than all your thoughts and feelings.",
        "Recognise your depth — and rest there.",
        "Everyone who breathes has the possibility of awakening.",
        "Awakening needs no permission — only willingness.",
        "Kindness toward yourself is the prerequisite for kindness toward others.",
        "What you cultivate within, you bring into the world.",
        "The universe is contained in every breath.",
        "Today is unique — it will never come again.",
        "Live it as the gift that it is.",
        "Whatever comes today, you can meet it.",
        "You are equipped for this moment.",
        "The path never ends — it always opens anew."
    )
}
